In [ ]:
#Salary predictin based on years of experience
#Linear regression model
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import sklearn
dataset= pd.read_csv('Salary.csv')
#print(dataset)

In [ ]:
dataset

In [ ]:
x = dataset.iloc[:, :1].values
print(x)

In [ ]:
y = dataset.iloc[:, 1:].values
print(y)

In [13]:
print(matplotlib.__version__)

3.6.3


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=0)
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [21]:
print(y_pred)

[[120057.87672477]
 [ 88127.64484315]
 [ 73456.99776241]
 [118331.91824468]
 [ 97620.41648363]
 [ 71731.03928232]
 [ 63101.24688189]]


In [20]:
print(y_test)

[[121872]
 [ 91738]
 [ 66029]
 [122391]
 [101302]
 [ 67938]
 [ 63218]]


In [ ]:
plt.scatter(x, y, color='r')
plt.plot(x, regressor.predict(x), color='blue')

In [23]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("regressor.pkl","wb")
pickle.dump(regressor , pickle_out)
pickle_out.close()

In [24]:
regressor.predict([[2]])

array([[46704.64132106]])